name: "Assets"

on:
  workflow_dispatch:

  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Generate version
        id: version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +'%Y%m%d')
          VERSION="0.0.0-$DATE-$COMMIT_HASH"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version
      - run: npm publish --provenance --access public --tag master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
